[package]
name = "welt-gen"
description = "Welt volet generation (wp-gen) - squelette Phase 0"
license = "GPL-3.0"
version.workspace = true
edition.workspace = true

[dependencies]
welt-core = { path = "../welt-core" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "noise_height_map"
harness = false
