//! Fixture generated by WPCore's EditorFilterOracle using the real Java filters.
use super::*;

struct Reader<'a> {
    bytes: &'a [u8],
    offset: usize,
}
impl Reader<'_> {
    fn int(&mut self) -> i32 {
        let value =
            i32::from_be_bytes(self.bytes[self.offset..self.offset + 4].try_into().unwrap());
        self.offset += 4;
        value
    }
    fn float(&mut self) -> f32 {
        f32::from_bits(self.int() as u32)
    }
    fn flag(&mut self) -> bool {
        let value = self.bytes[self.offset];
        self.offset += 1;
        assert!(value <= 1);
        value == 1
    }
    fn child(&mut self) -> Option<usize> {
        let index = self.int();
        if index == -1 {
            None
        } else {
            Some(index as usize)
        }
    }
}

struct Cell {
    height: i32,
    water: i32,
    slope: f32,
    terrain: i32,
    biome: i32,
    auto_biome: i32,
    lava: bool,
    selected: bool,
    annotations: i32,
    layers: Vec<i32>,
}
impl CellData for Cell {
    fn height(&self) -> i32 {
        self.height
    }
    fn water(&self) -> i32 {
        self.water
    }
    fn slope(&self) -> f32 {
        self.slope
    }
    fn terrain(&self) -> i32 {
        self.terrain
    }
    fn biome(&self) -> i32 {
        self.biome
    }
    fn auto_biome(&self) -> i32 {
        self.auto_biome
    }
    fn lava(&self) -> bool {
        self.lava
    }
    fn selected(&self) -> bool {
        self.selected
    }
    fn annotations(&self) -> i32 {
        self.annotations
    }
    fn layer(&self, plane: usize) -> i32 {
        self.layers[plane]
    }
}

#[test]
fn matches_real_java_filter_calls_bit_for_bit() {
    let bytes = include_bytes!("../../golden/editor_filter_java.bin");
    let mut r = Reader { bytes, offset: 0 };
    assert_eq!(r.int(), 0x57454631);
    let filters = r.int();
    assert_eq!(filters, 69);
    let mut total = 0;
    for filter in 0..filters {
        let count = r.int();
        let planes = r.int();
        let mut nodes = Vec::new();
        for _ in 0..count {
            nodes.push(match r.int() {
                0 => {
                    let kind = r.int();
                    let value = r.int();
                    let plane = r.int() as usize;
                    let predicate = match kind {
                        0 => Predicate::Terrain(value),
                        1 => Predicate::BitLayer(plane),
                        2 => Predicate::LayerAny(plane),
                        3 => Predicate::LayerEqual(plane, value),
                        4 => Predicate::LayerAtLeast(plane, value),
                        5 => Predicate::LayerAtMost(plane, value),
                        6 => Predicate::Biome(value),
                        7 => Predicate::Water,
                        8 => Predicate::Land,
                        9 => Predicate::Lava,
                        10 => Predicate::AutoBiome(value),
                        11 => Predicate::AnnotationAny,
                        12 => Predicate::Annotation(value),
                        _ => panic!("Unknown Java predicate"),
                    };
                    Node::Predicate {
                        predicate,
                        except: r.flag(),
                    }
                }
                1 => {
                    let count = r.int();
                    Node::Combined((0..count).map(|_| r.int() as usize).collect())
                }
                2 => {
                    let selection = r.int() as i8;
                    let except = r.child();
                    let only = r.child();
                    let kind = r.int();
                    let above = r.int();
                    let below = r.int();
                    let levels = match kind {
                        -1 => None,
                        0 => Some(Levels::Between(above, below)),
                        1 => Some(Levels::Outside(above, below)),
                        2 => Some(Levels::Above(above)),
                        3 => Some(Levels::Below(below)),
                        _ => panic!("Unknown Java level type"),
                    };
                    let feather = r.flag();
                    let check_slope = r.flag();
                    let slope = r.float();
                    let above = r.flag();
                    Node::Default {
                        selection,
                        except,
                        only,
                        levels,
                        feather,
                        slope: check_slope.then_some((slope, above)),
                    }
                }
                _ => panic!("Unknown Java node"),
            });
        }
        let program = Program::new(nodes, planes as usize).unwrap();
        for case in 0..r.int() {
            let cell = Cell {
                height: r.int(),
                water: r.int(),
                slope: r.float(),
                terrain: r.int(),
                biome: r.int(),
                auto_biome: r.int(),
                lava: r.flag(),
                selected: r.flag(),
                annotations: r.int(),
                layers: (0..planes).map(|_| r.int()).collect(),
            };
            let strength = r.float();
            let expected = r.int() as u32;
            let actual = program.modify_strength(&cell, strength);
            let bits = if actual.is_nan() {
                0x7fc00000
            } else {
                actual.to_bits()
            };
            assert_eq!(bits, expected, "filter {filter}, case {case}");
            total += 1;
        }
    }
    assert_eq!(total, 4968);
    assert_eq!(r.offset, bytes.len());
}
